"""S14 — freeze the sealed synthetic wall family (S9f) as scene files.

Until S14 the wall family existed only as code (``scripts/wall_resonde_S9f.build_scene_sealed``),
so its certificates could not be cross-checked against an authored scene with
``cnp verify <cert> <scene>``. This script writes ``scenes/wall/k{3..8}.yaml`` from exactly the
scenes the S9f bench certified (same sealing, same start/goal: ``s0hi = 4/5`` for k = 3..7 and
``1`` for the k = 8 frontier point, as ``scripts/run_resonde_S9f.py``), then proves the round trip:
each file, parsed back by ``scenes.load``, states the same problem as the in-memory scene
(``scenes.scene_matches_cert`` against the certificate header built from it).

Run: ``python scripts/export_wall_scenes.py``  (deterministic; re-running rewrites identical files)
"""
from __future__ import annotations

import os
import sys
from fractions import Fraction as F

import yaml

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

from cnp import certificate as cert, scenes   # noqa: E402
import wall_resonde_S9f as rs                  # noqa: E402

ROOT = os.path.abspath(os.path.join(HERE, ".."))
OUT = os.path.join(ROOT, "scenes", "wall")
S0HI = {3: F(4, 5), 4: F(4, 5), 5: F(4, 5), 6: F(4, 5), 7: F(4, 5), 8: F(1, 1)}
BUDGET_TIME_S = {k: 1800 for k in (3, 4, 5, 6, 7)} | {8: 300}

HEADER = """\
# Sealed synthetic wall, k = {k} active joints (S9f family, frozen as a scene file in S14).
#
# A {k}-joint spatial revolute chain (alternating yaw / pitch axes, 0.4 m links). The certified
# body is the LAST link, so it depends on all {k} joints: {k} active dimensions, none passive.
# The WALL box is sealed by Bernstein bounds of that link's reach over the band |s0| <= 1/10,
# |s_i| <= 1/4 (scripts/wall_resonde_S9f.py, _tight_seal): every configuration in the slab
# collides, provably, so this is a genuine disconnection by construction. Barrier phi = s0.
# Generated by scripts/export_wall_scenes.py — do not edit by hand.
"""
FRONTIER = """\
#
# k = 8 is the frontier point of the cost figure: its single per-leaf LP (about 2.3 million
# rows) outlasts the 300 s budget, and the verdict is UNDECIDED on budget — no certificate.
# UNDECIDED is not a proof of infeasibility, and not a proof of feasibility either.
"""


def _s(x) -> str:
    return str(cert.Q(x))


def scene_dict(sc: cert.Scene, k: int) -> dict:
    r = sc.robot
    return {
        "robot": {"kind": r.kind, "q_star": [_s(v) for v in r.q_star],
                  "joints": [{"offset": [_s(x) for x in j["offset"]],
                              "axis": [_s(x) for x in j["axis"]]} for j in r.joints]},
        "body": {"link": sc.body_link,
                 "hull_vertices": [[_s(c) for c in v] for v in sc.hull_vertices]},
        "obstacles": {nm: {"hrep": {"A": [[_s(x) for x in row] for row in A],
                                    "b": [_s(x) for x in b]}}
                      for nm, (A, b) in sc.obstacles.items()},
        "phi": {"degree_per_var": sc.phi_degree,
                "coeffs": {",".join(str(int(e)) for e in exps): _s(c)
                           for exps, c in sc.phi.items() if cert.Q(c) != 0}},
        "delta": _s(sc.delta),
        "box": [[_s(lo), _s(hi)] for lo, hi in sc.box],
        "start_s": [_s(v) for v in sc.start_s],
        "goal_s": [_s(v) for v in sc.goal_s],
        "pairs": list(sc.pairs),
        "lam_degree": sc.lam_degree,
        "budget": {"axis": "margin", "max_depth": rs.MAX_DEPTH, "max_leaves": rs.MAX_LEAVES,
                   "max_time_s": BUDGET_TIME_S[k]},
    }


def main() -> int:
    os.makedirs(OUT, exist_ok=True)
    for k in sorted(S0HI):
        sc = rs.build_scene_sealed(k, s0hi=S0HI[k])
        sc.lam_degree = "affine"
        path = os.path.join(OUT, f"k{k}.yaml")
        with open(path, "w") as f:
            f.write(HEADER.format(k=k) + (FRONTIER if k == 8 else "") + "\n")
            yaml.safe_dump(scene_dict(sc, k), f, sort_keys=False, width=100)
        loaded, budget = scenes.load(path)
        ok, why = scenes.scene_matches_cert(loaded, cert._certificate_header(sc))
        assert ok, f"k={k}: scene file does not round-trip: {why}"
        assert loaded.lam_degree == "affine" and budget.axis == "margin"
        assert budget.max_depth == rs.MAX_DEPTH and budget.max_time_s == BUDGET_TIME_S[k]
        print(f"written {os.path.relpath(path, ROOT)}  (round trip OK: {why})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
