"""S15 — docs/paper/TABLE-reproduce.md from one reproduce.json (numbers read, never retyped).

Usage: python scripts/make_table_reproduce.py [benchmarks/results/<stamp>/reproduce.json]
Default: the latest reproduce.json whose run started on a clean tree.
"""
from __future__ import annotations

import glob
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "docs", "paper", "TABLE-reproduce.md")

LABELS = {
    "relay": "Planar relay (E3)", "comb": "Comb", "anchor": "Shoulder–elbow (anchor)",
    "bin": "iiwa-like bin", "flagship": "iiwa7 shelf (flagship)", "crate": "iiwa7 stacked crate",
    "guard": "iiwa7 safety guard",
}


def _latest_clean() -> str:
    for path in sorted(glob.glob(os.path.join(ROOT, "benchmarks/results/*/reproduce.json")),
                       reverse=True):
        with open(path) as f:
            if json.load(f).get("git_dirty_at_start") is False:
                return path
    raise SystemExit("no clean-tree reproduce.json found")


def _s(x, nd=2) -> str:
    return "—" if x is None else f"{x:.{nd}f} s"


def _gt(r: dict) -> str:
    g = r.get("groundtruth") or {}
    if g.get("oracle") is None and "free_in_slab" not in g:
        return "—"
    parts = [f"{g.get('free_in_slab')} free / {g.get('n_uniform_in_slab', '?')} uniform"]
    if "free_in_slab_corner" in g:
        parts.append(f"{g['free_in_slab_corner']} free / "
                     f"{g.get('n_corner_biased_in_slab', '?')} corner-biased")
    if "free_at_slab_corners" in g:
        parts.append(f"{g['free_at_slab_corners']} free / {g['n_slab_corners']} slab corners")
    return " + ".join(parts)


def main(path: str) -> None:
    with open(path) as f:
        d = json.load(f)
    rows = d["rows"]
    rel = os.path.relpath(path, ROOT)
    L = [f"# Table §7.6 and figures of §7.4-§7.5 — read from `{rel}`", "",
         f"Generated by `scripts/make_table_reproduce.py`. Commit `{d['commit'][:10]}`, "
         f"`git_dirty_at_start = {str(d['git_dirty_at_start']).lower()}`, "
         f"run outputs only at end: `{str(d.get('tree_changes_are_run_outputs_only')).lower()}`. "
         f"Machine: {d['machine']['cpu']}, {d['machine']['ncpu']} cores, "
         f"{d['machine']['mem_gb']:.0f} GB, Python {d['machine']['python']}. "
         f"Load average (1/5/15 min) at start {d['load_avg_at_start']}, at end {d['load_avg_at_end']}.",
         "", "Engine = branch-and-bound decision alone; certify = scene load + FK build + engine + "
         "export; verify = exact verifier on the written certificate. One process per row.", "",
         "| row | DOF | active | leaves | verdict | engine | certify | verify | load before | "
         "stdlib re-check | CLI re-check | ground truth |",
         "|---|---|---|---|---|---|---|---|---|---|---|---|"]
    for key, r in rows.items():
        label = LABELS.get(key, key.replace("wall_k", "Sealed wall, k = "))
        std = r.get("recheck_stdlib_verify_file") or {}
        cli = r.get("recheck_cli_verify_with_scene") or {}
        stdtxt = "—" if not std else (
            f"{'OK' if std.get('ok') else 'FAIL'}, third-party modules: "
            f"{len(std.get('third_party_modules_loaded') or [])}")
        verdict = r["verdict"] + ("" if r.get("termination") == "certified"
                                  else f" ({r.get('termination')})")
        L.append(f"| {label} | {r['dof']} | {r.get('n_active', '—')} | {r['leaves']} | {verdict} | "
                 f"{_s(r.get('engine_s'))} | {_s(r.get('certify_s'))} | {_s(r.get('verify_s'), 3)} | "
                 f"{r.get('load_avg_before', ['—'])[0]} | {stdtxt} | "
                 f"{'—' if not cli else ('OK' if cli.get('ok') else 'FAIL')} | {_gt(r)} |")
    f7 = rows["flagship"]
    ph, bd = f7["phases_s"], f7["export_breakdown_s"]
    L += ["", "## Flagship decomposition (§5, §6.3, §7.5)", "",
          f"- certify {f7['certify_s']:.1f} s = FK build {ph['load_and_fk_build']:.1f} s + "
          f"branch-and-bound {ph['engine']:.1f} s + export {ph['export']:.1f} s",
          f"- of the export, the exact verifier twice: full verify loop "
          f"{bd['verify_loop_full_verifier']:.2f} s + per-leaf audit {bd['per_leaf_exact_audit']:.2f} s "
          f"= {bd['verify_loop_full_verifier'] + bd['per_leaf_exact_audit']:.1f} s",
          f"- verify {f7['verify_s']:.2f} s; reduced LP {f7['lp_reduced']['rows']} rows × "
          f"{f7['lp_reduced']['cols']} columns vs {f7['lp_full']['rows']} full "
          f"({f7['reduction_x']:.0f}×)", "",
          "## Certificate statistics (all certified rows)", ""]
    for key, r in rows.items():
        cs = r.get("cert_stats")
        if cs:
            L.append(f"- {key}: re-solve failures {cs['n_reresolve_failed']}, embedded "
                     f"{cs['n_leaves_embedded']}, re-solved {cs['n_leaves_resolved']}, "
                     f"embeddings rejected {cs['n_embed_rejected']}")
    k8 = rows.get("wall_k8")
    if k8:
        L += ["", f"k = 8: {k8['verdict']} ({k8.get('termination')}), engine {k8['engine_s']:.1f} s "
              f"against the 300 s budget (a single LP is atomic)."]
    with open(OUT, "w") as f:
        f.write("\n".join(L) + "\n")
    print(f"written {os.path.relpath(OUT, ROOT)} from {rel}")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else _latest_clean())
